# Generated by Django 6.0 on 2025-12-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='timestamp',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='otp_created_at',
            new_name='otp_time',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='phone',
        ),
        migrations.AddField(
            model_name='voter',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='voter',
            name='email',
            field=models.EmailField(default='anjalidummy1234@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voter',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
