# Generated by Django 6.0 on 2025-12-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0002_election_rename_timestamp_vote_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
