# Generated by Django 6.0 on 2025-12-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0002_voter_otp_voter_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
