# Generated by Django 6.0 on 2025-12-22 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0003_voter_device_id_alter_voter_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='constituency',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
