# Generated by Django 6.0 on 2025-12-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0003_voter_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
