# Generated by Django 6.0 on 2025-12-22 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0004_voter_constituency'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='voted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
