# Generated by Django 6.0 on 2025-12-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0005_vote_created_at'),
        ('voting_app', '0005_vote_voted_at'),
    ]

    operations = [
    ]
